version: '3.7'
services:
  mysql-database:
    container_name: mysql-database
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - ./app/.env.dev
    expose:
      - 3306
    restart: on-failure
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.16.5.2

  redis-database:
    image: redis
    container_name: redis-database
    ports:
      - 6379:6379
    expose:
      - 6379
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.16.5.4

  node-server:
    container_name: node-server
    build: ./app
    ports:
      - 80:80
    environment:
      - PORT=80
      - NODE_ENV=dev
    env_file:
      - ./app/.env
      - ./app/.env.dev
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mysql-database
      - redis-database
    entrypoint:
      - ./docker-entrypoint.sh
    networks:
      backend:
        ipv4_address: 172.16.5.3

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.5.0/16
