version: '3.7'
services: 
  mysql-database:
    container_name: mysql-database
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: haibt_bread
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    expose: 
      - 3306
    restart: on-failure
    volumes: 
      - ./db/data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.16.5.2
    
  node-server:
    container_name: node-server
    build: .
    ports: 
      - 3000:3000
    environment: 
      NODE_ENV: dev
      PORT: 3000
      DB_URL: mysql://admin:admin@172.16.5.2/haibt_bread
    volumes:
      - .:/usr/src/app
    depends_on: 
      - mysql-database
    command: npm run dev
    networks:
      backend:
        ipv4_address: 172.16.5.3

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.5.0/16