version: '3.7'
services: 
  mysql-database:
    container_name: mysql-database
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - ./.env.prod
    expose: 
      - 3306
    restart: on-failure
    volumes: 
      - ./db/data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.16.5.2
    
  node-server:
    container_name: node-server
    build: .
    ports: 
      - 3000:3000
    env_file: 
      - ./.env
      - ./.env.dev
    volumes:
      - .:/usr/src/app
    depends_on: 
      - mysql-database
    command: >
      sh -c "ENV=prod npm run prisma:generate &&
            ENV=prod npm run prisma:up &&
            npm start"
    networks:
      backend:
        ipv4_address: 172.16.5.3

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.5.0/16