version: '3.7'
services: 
  mysql-database:
    container_name: mysql-database
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'prography-test'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    restart: on-failure
    volumes: 
      - ./db/data:/var/lib/mysql
    
  node-server:
    container_name: node-server
    build: .
    ports: 
      - '3000:3000'
    environment: 
      NODE_ENV: 'dev'
    volumes:
      - '.:/usr/src/app'
    depends_on: 
      - mysql-database
    command: 'npm run dev'