version: '3.7'
services:
  node-server-green:
    container_name: node-server-green
    build: .
    ports: 
      - 4000:3000
    environment:
      - NODE_ENV=prod
    env_file: 
      - ./.env
      - ./.env.prod
    volumes:
      - .:/usr/src/app
    entrypoint: 
      - ./docker-entrypoint.sh
    networks:
      habitbread:
        ipv4_address: 172.16.5.6

networks:
  habitbread:
    external: true