version: '3.7'
services:
  node-server-blue:
    container_name: node-server-blue
    build: ./app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=prod
    env_file:
      - ./app/.env
      - ./app/.env.prod
    volumes:
      - ./app:/usr/src/app
    entrypoint:
      - ./docker-entrypoint.sh
    networks:
      habitbread:
        ipv4_address: 172.16.5.5

networks:
  habitbread:
    external: true
