version: '3.7'
services: 
  mysql-database:
    container_name: mysql-database
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - ./.env.dev
    expose: 
      - 3306
    restart: always
    volumes: 
      - ./db/data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.16.5.2

  redis-database:
    image: redis
    container_name: redis-database
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      backend:
        ipv4_address: 172.16.5.4

  node-server:
    container_name: node-server
    build: .
    ports: 
      - 3000:3000
    environment:
      - NODE_ENV=dev
    env_file: 
      - ./.env
      - ./.env.dev
    volumes:
      - .:/usr/src/app
    depends_on: 
      - mysql-database
      - redis-database
    command:
      - /bin/bash
      - -c
      - "dockerize -wait tcp://mysql-database:3306 -timeout 10s
        && ENV=dev npm run prisma:generate
        && ENV=dev npm run prisma:up
        && npm run dev"
    networks:
      backend:
        ipv4_address: 172.16.5.3

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.5.0/16