version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: "12.16"
    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: 
          name: Run Test 
          command: |
            node --version
            ENV=test npm run prisma:generate
            ENV=test npm run prisma:up
            npm test
  # The machine executor supports Docker Layer Caching which is useful when you are building Docker images during your job or Workflow.
  deploy-stage:
    machine:
      enabled: true
    
    steps:
      - add_ssh_keys:
          fingerprints: 
            - be:b1:2e:1b:12:f8:cb:fc:7e:55:f7:f3:1d:ea:b9:9e
      - run:
          name: Deploy Over SSH
          # docker stop prography-server
          # docker build -t prography-team4-node-server:latest .
          # docker run -p 3000:3000 -d --rm=true --name prography-server prography-team4-node-server:latest
          # docker ps -a
          command: |
            ssh $SSH_USER@$SSH_HOST \<< EOF
              echo "Deploy Over SSH"
              cd circleci-node-test
              git checkout $CIRCLE_BRANCH
              git pull
            EOF
workflows:
    server-testing:
      jobs:
        - build-and-test:
            filters:
              branches:
                only:
                  - /feature-.*/
                  - develop
                  - master
    # server-deploy:
    #   jobs:
    #     - build-and-test
    #     - deploy-stage:
    #         requires:
    #           - build-and-test
    #         filters:
    #           branches:
    #             only: 
    #               - master
                  # - develop
