# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Node.js CD - Continuous Deployment

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-deploy:
#     name: Build and Deploy
#     runs-on: ubuntu-latest
#     # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
#     container: node:12 

#     steps:
#       - uses: actions/checkout@v2

#       - name: Use Node.js 12.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: '12.x'

#       - name: Deploy Node Server
#         run : 
#         env:
#           # The hostname used to communicate with the Redis service container
#           REDIS_HOST: redis
#           # The default Redis port
#           REDIS_PORT: 6379
