# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD - Continuous Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
    container: node:12

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Deploy Node Server
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.DEPLOY_SERVER }} << EOF
            echo "Start Blue-Green Deploy !"
            cd /home/ubuntu/6th-team4-node
            git checkout master
            git pull origin feature/wwlee94/auto-deploy
            /bin/bash ./deploy.sh
          EOF
