# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        max-parallel: 2
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create .env file
      run: 
        echo "PORT = 3001" >> .env.test
        echo "DB_URL = ${{secrets.DB_URL_TEST}}" >> .env.test 

    - name: Install Dependencies
      run: |
        npm ci
        npm run build --if-present

    - name: Prisma generate and migrate up
      run: |
        ENV=test npm run prisma:generate
#        ENV=test npm run prisma:up

    - name: Run Test
      run : npm test
